//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tbl_Users
    {
        [Display(Name = "USER ID")]
        public int user_ID { get; set; }
        [Display(Name = "USER NAME")]
        [Required]
        public string user_Name { get; set; }
        [Display(Name = "EMAIL ADDRESS")]
        [Required]
        [EmailAddress]
        public string email { get; set; }
    }
}
